# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false
    cache:                  true
    error_reporting:        <?php echo (E_ERROR)."\n" ?>

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

all: 
  .actions:
    login_module:  authenticate
    login_action:  login

    secure_module: authenticate
    secure_action: secure

    error_404_module: frontend
    error_404_action: error404

  .settings:
    standard_helpers: [Partial, I18N, Text]
  
    # Form security secret (CSRF protection)
    csrf_secret:            2cac58d988bee93232aa8ece941b08219f4fc45d

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    charset: utf-8
    i18n: false
    default_culture: fr