generator:
  class: sfDoctrineGenerator
  param:
    model_class:           juryman
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          juryman
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Jurymen list
      filter:  ~
      form:    ~
      edit:
        title: Juryman edition
      new:
        title: New juryman
