generator:
  class: sfDoctrineGenerator
  param:
    model_class:           challenge
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          challenge
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Challenges list
      filter:  ~
      form:    ~
      edit:
        title: Challenge edition
      new:
        title: New challenge
