generator:
  class: sfDoctrineGenerator
  param:
    model_class:           presentation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          presentation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Presentation list
      filter:  ~
      form:    ~
      edit:
        title: Presentation edition
      new:
        title: New presentation
